development:
  adapter: postgresql
  database: pinterestclone_development
  pool: 5
  timeout: 5000
  host: 5432
  user: postgres
  password: itstheremixtoignition

production:
  adapter: postgresql
  database: pinterestclone_production
  encoding: unicode
  pool: 5
  timeout: 5000
