development:
  adapter: postgresql
  database: Tack_development
  pool: 5
  timeout: 5000
  post: 5432
  user: postgres
  password: itstheremixtoignition

production:
  adapter: postgresql
  database: Tack_production
  encoding: unicode
  pool: 5
  timeout: 5000